package com.payment;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BankWebServiceService service = new BankWebServiceService();
 * BankWebServiceDelegate portType = service.getBankWebServicePort();
 * portType.setPayment(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BankWebServiceService", targetNamespace = "http://bankwebser.com/", wsdlLocation = "http://localhost:9999/BankWebServer/BankWebServicePort?wsdl")
public class BankWebServiceService extends Service {

	private final static URL BANKWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.payment.BankWebServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.payment.BankWebServiceService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9999/BankWebServer/BankWebServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/BankWebServer/BankWebServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BANKWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public BankWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BankWebServiceService() {
		super(BANKWEBSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://bankwebser.com/", "BankWebServiceService"));
	}

	/**
	 * 
	 * @return returns BankWebServiceDelegate
	 */
	@WebEndpoint(name = "BankWebServicePort")
	public BankWebServiceDelegate getBankWebServicePort() {
		return super.getPort(new QName("http://bankwebser.com/",
				"BankWebServicePort"), BankWebServiceDelegate.class);
	}

}
