package com.pref;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserPreferenceService service = new UserPreferenceService();
 * UserPreferenceDelegate portType = service.getUserPreferencePort();
 * portType.main(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserPreferenceService", targetNamespace = "http://service.com/", wsdlLocation = "http://localhost:9999/eCommerce/UserPreferencePort?wsdl")
public class UserPreferenceService extends Service {

	private final static URL USERPREFERENCESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.pref.UserPreferenceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.pref.UserPreferenceService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9999/eCommerce/UserPreferencePort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/eCommerce/UserPreferencePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERPREFERENCESERVICE_WSDL_LOCATION = url;
	}

	public UserPreferenceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserPreferenceService() {
		super(USERPREFERENCESERVICE_WSDL_LOCATION, new QName(
				"http://service.com/", "UserPreferenceService"));
	}

	/**
	 * 
	 * @return returns UserPreferenceDelegate
	 */
	@WebEndpoint(name = "UserPreferencePort")
	public UserPreferenceDelegate getUserPreferencePort() {
		return super.getPort(new QName("http://service.com/",
				"UserPreferencePort"), UserPreferenceDelegate.class);
	}

}
